### ISSUE TITLE
测试集

### ISSUE THREAD

**Issue by yxk9810** [china-ai-law-challenge/CAIL2024#3]
1.请问测试集什么时候公布？

**Comment by helloxcq** [comment]
您好，测试集已发布！

**Comment by yxk9810** [comment]
[cpwsslsc](https://github.com/china-ai-law-challenge/CAIL2024/tree/main/cpwsslsc) ,比如这个我看
![image](https://github.com/user-attachments/assets/abdfcbd1-9324-421f-84bf-468d94ad0669)
，http://cail.cipsc.org.cn/task_summit.html?raceID=1&cail_tag=2024官网也只有个训练数据，没有测试集

**Comment by helloxcq** [comment]
![微信图片_20240929115624](https://github.com/user-attachments/assets/0bacc2c4-5d34-46e6-8726-0227c4cdcf0f)
有测试集啊。
